-- ExpenseCategory enum에 CARRYOVER 추가 (이전 달 이월 지출 식별용)
ALTER TABLE `expenses`
  MODIFY COLUMN `category` ENUM(
    'TRANSPORTATION','FOOD','GROCERIES','LEISURE','LIVING',
    'MEDICAL','EDUCATION','ALLOWANCE','CELEBRATION','ASSET_TRANSFER',
    'CHILDCARE','COMMUNICATION','CARRYOVER','OTHER'
  ) NULL;

ALTER TABLE `budgets`
  MODIFY COLUMN `category` ENUM(
    'TRANSPORTATION','FOOD','GROCERIES','LEISURE','LIVING',
    'MEDICAL','EDUCATION','ALLOWANCE','CELEBRATION','ASSET_TRANSFER',
    'CHILDCARE','COMMUNICATION','CARRYOVER','OTHER'
  ) NOT NULL;

ALTER TABLE `budget_templates`
  MODIFY COLUMN `category` ENUM(
    'TRANSPORTATION','FOOD','GROCERIES','LEISURE','LIVING',
    'MEDICAL','EDUCATION','ALLOWANCE','CELEBRATION','ASSET_TRANSFER',
    'CHILDCARE','COMMUNICATION','CARRYOVER','OTHER'
  ) NOT NULL;
