-- AlterEnum
ALTER TABLE `notification_settings` MODIFY COLUMN `category` ENUM('SCHEDULE','TODO','HOUSEHOLD','SAVINGS','ASSET','CHILDCARE','GROUP','SYSTEM') NOT NULL;

-- AlterEnum
ALTER TABLE `notifications` MODIFY COLUMN `category` ENUM('SCHEDULE','TODO','HOUSEHOLD','SAVINGS','ASSET','CHILDCARE','GROUP','SYSTEM') NOT NULL;
