-- AlterTable
ALTER TABLE `notification_settings` ADD COLUMN `routineReminderHour` INTEGER NOT NULL DEFAULT 21;

-- AlterEnum
ALTER TABLE `notification_settings` MODIFY COLUMN `category` ENUM('SCHEDULE','TODO','HOUSEHOLD','SAVINGS','ASSET','CHILDCARE','GROUP','SYSTEM','WEATHER','FRIDGE','ROUTINE') NOT NULL;

-- AlterEnum
ALTER TABLE `notifications` MODIFY COLUMN `category` ENUM('SCHEDULE','TODO','HOUSEHOLD','SAVINGS','ASSET','CHILDCARE','GROUP','SYSTEM','WEATHER','FRIDGE','ROUTINE') NOT NULL;
