-- AlterEnum: ExpenseCategory에 GROCERIES 추가
ALTER TABLE `expenses` MODIFY COLUMN `category` ENUM('TRANSPORTATION', 'FOOD', 'GROCERIES', 'LEISURE', 'LIVING', 'MEDICAL', 'EDUCATION', 'ALLOWANCE', 'CELEBRATION', 'ASSET_TRANSFER', 'CHILDCARE', 'COMMUNICATION', 'OTHER') NULL;

ALTER TABLE `budgets` MODIFY COLUMN `category` ENUM('TRANSPORTATION', 'FOOD', 'GROCERIES', 'LEISURE', 'LIVING', 'MEDICAL', 'EDUCATION', 'ALLOWANCE', 'CELEBRATION', 'ASSET_TRANSFER', 'CHILDCARE', 'COMMUNICATION', 'OTHER') NOT NULL;

ALTER TABLE `budget_templates` MODIFY COLUMN `category` ENUM('TRANSPORTATION', 'FOOD', 'GROCERIES', 'LEISURE', 'LIVING', 'MEDICAL', 'EDUCATION', 'ALLOWANCE', 'CELEBRATION', 'ASSET_TRANSFER', 'CHILDCARE', 'COMMUNICATION', 'OTHER') NOT NULL;
