-- AlterEnum: PermissionCategory에 CHILDCARE 추가
ALTER TABLE `permissions` MODIFY COLUMN `category` ENUM('GROUP', 'TASK', 'CHILDCARE') NOT NULL DEFAULT 'GROUP';

-- AlterEnum: PermissionCode에 MANAGE_CHILDCARE 추가
ALTER TABLE `permissions` MODIFY COLUMN `code` ENUM('INVITE_MEMBER', 'DELETE_GROUP', 'UPDATE_GROUP', 'MANAGE_ROLE', 'MANAGE_MEMBER', 'READ_TASK', 'CREATE_TASK', 'UPDATE_TASK', 'DELETE_TASK', 'MANAGE_CATEGORY', 'MANAGE_CHILDCARE') NOT NULL;
